version: "3"
services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./:/var/lib/mysql"
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./env/mysql.env
    depends_on:
      - mysql
